name: Docker image buildx and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: docker image Build 
        run: docker build -t jtywfg/flask-redis:latest .
      -
        name: list docker image
        run: docker image ls
      -
        name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: docker tag
        run: docker tag  jtywfg/flask-redis flask-redis
      -
        name: push to dockerhub
        run: docker push wwffggle/flask-redis
        
